### ISSUE TITLE
Inference (on a specific spectrum)  some errors.

### ISSUE THREAD

**Issue by zhouyangit** [MarklandGroup/NMR2Struct#8]
Hello, I seem to have encountered some problems:
My my_inference_config.yaml configuration is as follows:

```
global_args:
  ngpus: 1
  dtype: float32
  savedir: "./results"
  seed: 42

model:
  model_type: "MultiTaskModel"
  load_model: null
  model_args:
    src_embed: ConvolutionalEmbedding
    src_embed_options:
      d_model: 128
      n_hnmr_features: 28000
      n_cnmr_features: 80
      use_hnmr: True
      use_cnmr: True
    forward_fxn: src_fwd_fxn_conv_embedding
    substructure_model: "EncoderModel"
    substructure_model_args:
      d_model: 128
      d_out: 957
      dim_feedforward: 1024
      nhead: 4
      num_layers: 4
      output_head: SingleLinear
      output_head_opts:
        d_model: 128
        d_out: 957
      pooler: SeqPool
      pooler_opts:
        d_model: 128
      source_size: 28045
      src_embed: null
      src_embed_options: {}
      src_forward_function: src_fwd_fxn_packed_tensor
      src_pad_token: null
    structure_model: "TransformerModel"
    structure_model_args: 
      src_embed: null
      src_embed_options: {}
      tgt_embed: "nn.embed"
      tgt_embed_options: {}
      src_forward_function: "src_fwd_fxn_packed_tensor"
      tgt_forward_function: "tgt_fwd_fxn_basic"
      source_size: 28045
      target_size: 24
      d_model: 128
      dim_feedforward: 1024
      src_pad_token: null 
      tgt_pad_token: 21
    substructure_model_ckpt: null
    structure_model_ckpt: "checkpoints/multitask_checkpoint.pt"
inference:
  model_selection: lowest
  splits: null
  dloader_args:
    shuffle: false
    batch_size: 1
  sets_to_run: ['test']
  run_inference_args: 
    pred_gen_fn: 'infer_transformer_model'
    pred_gen_opts:
      num_pred_per_tgt: 15 
      sample_val: 5 
      tgt_start_token: 22
      tgt_stop_token: 23 
      track_gradients: false
      alphabet: "example_configs/alphabet.npy"
      decode: true 
      infer_fwd_fxn: multitask
    write_freq: 100
```

### And then run.

```shell
 nmr_infer_single_spectrum --config my_inference_config.yaml --hnmr_file test_hnmr.txt --cnmr_file None --hnmr_shifts example_configs/HNMR_shifts.p --cnmr_shifts example_configs/CNMR_shifts.p --ckpt checkpoints/multitask_checkpoint.pt --normalize
```

result:  predictions_dataset_0_0.h5

but, predictions_dataset_0_0.h5   is as follows:

```
processed_predictions.h5
├── test
│   ├──predictions
│   │── scores
│   │── targets
└── 
```
### It's not this structure.
```
├── test
│   ├── bad_predictions
│   │   ├── predictions
│   │   ├── scores
│   │   └── targets
│   └── valid_predictions
│       ├── 0
│       │   ├── num_heavy_atoms
│       │   ├── prediction_bce_losses
│       │   ├── prediction_scores
│       │   ├── prediction_strings
│       │   └── target
│       └── ...
└── ...
```
May I ask at which specific step did I make a mistake?  Thank you very much.
